name: nixtla
channels:
  - conda-forge
dependencies:
  - dask<=2024.2.1
  - hierarchicalforecast
  - httpx
  - jupyterlab
  - neuralforecast
  - pandas
  - plotly
  - pydantic
  - pyreadr
  - pyspark>=3.3
  - requests
  - statsforecast
  - tenacity
  - utilsforecast>=0.1.7
  - pip:
    - black
    - cryptocmd
    - datasetsforecast
    - fire
    - flake8
    - fugue[ray]>=0.8.7
    - holidays
    - mypy
    - nbdev
    - python-dotenv
    - ray[serve-grpc]<2.6.3
    - tabulate
